version: "3.8"
services:
  proxy:
    image: nginx:1.19.7-alpine
    volumes:
      - ./proxy/development/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - 80:80
    depends_on:
      - web

  web:
    build:
      context: .
      target: development
      # args:
      #   RAILS_ENV: ${RAILS_ENV}
      #   RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    restart: always
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      # - ./log:/app/log
      - .:/app
      - type: tmpfs
        target: /app/tmp/pids/
    tty: true
    stdin_open: true
    depends_on:
      - db
      - cache
    env_file: .env
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}

  system-test-web:
    build:
      context: .
      target: development
    restart: always
    command: bundle exec rails s -p 5017 -b 0.0.0.0
    ports:
      - 5017:5017
    volumes:
      - .:/app
      - type: tmpfs
        target: /app/tmp/pids/
    tty: true
    stdin_open: true
    depends_on:
      - db
      - cache
      - public
    env_file: .env
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      SYSTEM_TEST: 1

  db:
    image: mysql:5.7.32
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  public:
    build:
      context: .
      target: development
    command: ./bin/webpack-dev-server
    ports:
      - 3035:3035
    volumes:
      - .:/app
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0

  cache:
    image: redis:5.0.6-alpine3.10
    volumes:
      - cache-data:/data
    restart: always

volumes:
  db-data:
  cache-data:
